Add retry config for throttling errors
fauna/fauna-python pull request #146
Opened 2023-08-30 15:29 UTC by pnwpedro

Ticket(s): BT-3465

## Problem

ThrottlingError is very retryable, but we don't currently retry.

## Solution

* Implement a basic exponential backoff retry strategy for ThrottlingError.
* Expose RetryPolicy configuration at the client level
* Default the RetryPolicy to 3 max attempts and a maximum backoff of 20 seconds

## Testing

Added unit tests. Existing integ tests pass.

----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-08-30 15:37 UTC, sprsquish requested changes
The docs are going to need to be updated.

2023-08-30 16:54 UTC, sprsquish requested changes

2023-08-30 16:54 UTC, sprsquish commented on fauna/client/retryable.py
> +      except ThrottlingError as e:
This should catch 502 as well.

2023-08-31 16:44 UTC, sprsquish submitted a review, later dismissed

2023-08-31 16:51 UTC, pnwpedro commented on fauna/client/client.py
> +        event of a ThrottlingError.
```suggestion
        event of a 429 or 502.
```

2023-08-31 16:51 UTC, pnwpedro commented on fauna/client/client.py
> +        of a ThrottlingError.
```suggestion
        of a 429 or 502.
```

2023-08-31 16:54 UTC, merged