Python 3.12 Support
fauna/fauna-python pull request #149
Opened 2023-10-02 15:25 UTC by cynicaljoy

Ticket(s): BT-###, FE-###,...

## Problem

Explain the context and why you're making that change. What is the problem you're trying to solve? In some cases there is not a problem and this can be thought of being the motivation for your change.

## Solution

Describe the modifications you've done.

## Result

What will change as a result of your pull request? Note that sometimes this section is unnecessary because it is self-explanatory based on the solution.

## Testing

Describe the manual and automated tests you completed to verify the change is working as expected.

----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-02 17:01 UTC, CLBray requested changes
Let's wait to declare that we support 3.12 until we've tested with the final 3.12 release. We shouldn't declare support using rc3 tests.

2023-10-04 17:54 UTC, CLBray requested changes

2023-10-04 17:54 UTC, CLBray commented on tests/docker-compose-tests.yml
> +    image: python:3.12.0rc3-alpine3.18
Still using rc3 image

2023-10-04 19:06 UTC, cynicaljoy commented on tests/docker-compose-tests.yml
> +    image: python:3.12.0rc3-alpine3.18
thanks for catching that

2023-10-04 19:15 UTC, CLBray approved these changes

2023-10-04 19:43 UTC, merged